```{r}
# import packages
library(tidyverse) 
#imdbRecent <- read.csv("action.csv")
#imdbOld <- read.csv("IMDB-Movie-Data.csv")

imdbRecentClean = imdbRecent[c("year","genre")]

imdbRecentClean
str(imdbRecentClean)
example_clean <- example %>%
  pivot_wider(names_from = variable, values_from = estimate)

example_clean
str(imdbRecentClean)
imdbOldClean = imdbOld[c("Year","Genre")]
head(imdbOldClean)

```

```{r}
library(tidyverse) 

imdb <- read.csv("IMDB-Movie-Data.csv")

imdb <- imdb %>%
  select(Genre, Year, Votes)

imdbClean <- imdb %>%
  separate(Genre, c('Genre', 'Genre1', 'Genre2'), ',') 

imdbCleanTest <- imdbClean %>%
  pivot_longer(cols = c(1:3), names_to = 'Random', values_to = 'Genre') 


imdbCleanTest <- imdbCleanTest %>%
  select(Genre, Year, Votes)

imdbCleanNA <- na.omit(imdbCleanTest)
<<<<<<< HEAD
<<<<<<< HEAD

```

```{r}
ggplot(imdbCleanNA, aes(x = as.character(Year), y = Votes, fill = Genre)) + geom_bar(stat = "identity") + labs(title = "Number of Votes for Each Genre Per Year", x = "Year") + theme_minimal()
```
=======
imdbCleanNA
```
>>>>>>> 660c3e3 (First_Plot_Trial)
=======
imdbCleanNA
```
>>>>>>> 660c3e3 (First_Plot_Trial)
